baseURL = "https://sgp2021.github.io/"
languageCode = "en-us"
title = "Symposium on Geometry Processing"
theme = "minimalConference"
[menu]
  [[menu.main]]
    name = "Submit"
    url = "/submit/"
    weight = 1
  [[menu.main]]
    name = "Organization"
    url = "/organization/"
